services:
  mysql:
    image: mysql:latest
    container_name: cdsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cdsdb
    ports:
      - "3307:3306"  

  cdsapi:
    build: ./cdsapi
    container_name: cdsapi
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cdsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
